FROM ruby:2.3.1
# COPY . /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./
ENV RAILS_ENV production
RUN gem install bundler -v '1.16.0'
RUN bundle install \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt install -y nodejs
ENTRYPOINT ./entrypoint.sh



