FROM ruby:2.4.0-alpine
# FROM ruby:2.4.0-slim
# FROM ruby:2.4.0
WORKDIR /app
COPY Gemfile ./
COPY Gemfile Gemfile.lock ./
ENV RAILS_ENV production
RUN apk update
RUN apk add --update build-base libxml2-dev 
RUN apk add --no-cache libxslt-dev
RUN apk add --no-cache bash
RUN apk add --no-cache openssl-dev
RUN apk add --no-cache libpq postgresql-client\
                       sqlite-dev libxslt-dev\
                       postgresql-dev\
                       curl
RUN gem install bundler -v 1.17.3
# RUN gem install pg
RUN bundle install
RUN apk add nodejs
COPY . /app
RUN bundle exec rake assets:precompile
RUN chmod +x ./entrypoint.sh
EXPOSE 3000


CMD ["rails", "server", "-b", "0.0.0.0"]